#version: "3.7"

services:
  postgres:
    image: postgres:14
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init-data.sh:/docker-entrypoint-initdb.d/init-data.sh
    networks:
      - dokploy-network
    ports:
      - 5432:5432
    environment:
      - POSTGRES_PASSWORD=2ee66f1cff906c19d564b8ce578a85b5
      - PG_MAX_CONNECTIONS=500
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == manager
      resources:
        limits:
          cpus: "1"
          memory: 1024M

volumes:
  postgres_data:
    external: true    

networks:
  dokploy-network:
    external: true    
